version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.config:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - '3000:3000' (because nginx is added)
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
